"""Generate diverse market participant personas for LLM agents."""

import logging

import numpy as np

from app.models.agent_profile import (
    AGENT_COMPOSITION,
    ARCHETYPE_PERSONAS,
    TraderProfile,
)
from app.services.llm_client import LLMClient, SONNET_MODEL

logger = logging.getLogger(__name__)


def generate_profiles_deterministic(
    total_agents: int = 50,
    composition: dict[str, float] | None = None,
    seed: int = 42,
) -> list[TraderProfile]:
    """
    Generate agent profiles using archetype templates (no LLM calls).

    This is the fast, deterministic path for testing and when LLM is unavailable.

    Args:
        total_agents: Total number of agents to create.
        composition: Dict of trader_type → fraction. Must sum to ~1.0.
        seed: Random seed for reproducibility.

    Returns:
        List of TraderProfile instances.
    """
    comp = composition or AGENT_COMPOSITION
    rng = np.random.default_rng(seed)
    profiles: list[TraderProfile] = []

    for trader_type, fraction in comp.items():
        count = max(1, round(total_agents * fraction))
        persona_template = ARCHETYPE_PERSONAS.get(trader_type, "You are a market participant.")

        for i in range(count):
            risk = float(rng.beta(2, 2))  # centered around 0.5
            capital = float(rng.lognormal(mean=9.0, sigma=1.0))  # ~$8000 median

            # Add behavioral variation
            biases = ["overconfidence", "loss_aversion", "herd", "contrarian", "anchoring", "recency"]
            bias = rng.choice(biases)

            horizons_by_type = {
                "hft": "scalper",
                "institutional": "swing",
                "noise": rng.choice(["scalper", "intraday", "swing"]),
            }
            horizon = horizons_by_type.get(trader_type, "intraday")

            profiles.append(
                TraderProfile(
                    agent_id=f"{trader_type}_{i:03d}",
                    trader_type=trader_type,
                    persona=persona_template,
                    risk_appetite=risk,
                    capital=capital,
                    information_edge=_default_edge(trader_type),
                    time_horizon=horizon,
                    behavioral_bias=bias,
                )
            )

    return profiles[:total_agents]


def _default_edge(trader_type: str) -> str:
    """Default information edge description by type."""
    edges = {
        "informed": "Proprietary order flow analysis and on-chain data",
        "noise": "None - trades for liquidity or entertainment",
        "momentum": "Technical analysis of price trends and volume",
        "mean_reversion": "Statistical mean-reversion signals from rolling averages",
        "fundamental": "Fair value model based on macroeconomic indicators",
        "hft": "Ultra-low latency order book microstructure analysis",
        "institutional": "Large portfolio rebalancing needs from fund allocation",
    }
    return edges.get(trader_type, "None")


async def generate_profiles_llm(
    total_agents: int = 50,
    composition: dict[str, float] | None = None,
    llm_client: LLMClient | None = None,
    seed: int = 42,
) -> list[TraderProfile]:
    """
    Generate unique, diverse agent personas using Claude Sonnet.

    Each agent gets a unique persona description generated by LLM.
    Falls back to deterministic generation on LLM failure.

    Args:
        total_agents: Total number of agents to create.
        composition: Dict of trader_type → fraction.
        llm_client: LLM client instance.
        seed: Random seed.

    Returns:
        List of TraderProfile instances with LLM-generated personas.
    """
    comp = composition or AGENT_COMPOSITION
    rng = np.random.default_rng(seed)
    client = llm_client or LLMClient(model=SONNET_MODEL)
    profiles: list[TraderProfile] = []

    for trader_type, fraction in comp.items():
        count = max(1, round(total_agents * fraction))

        # Generate personas in batch for this type
        prompt = _build_persona_prompt(trader_type, count)
        try:
            response = await client.achat(
                messages=[{"role": "user", "content": prompt}],
                model=SONNET_MODEL,
                temperature=0.9,
                max_tokens=2000,
            )
            personas = _parse_persona_response(response, count)
        except Exception as e:
            logger.warning(f"LLM persona generation failed for {trader_type}: {e}. Using defaults.")
            personas = [ARCHETYPE_PERSONAS.get(trader_type, "You are a market participant.")] * count

        for i, persona in enumerate(personas[:count]):
            risk = float(rng.beta(2, 2))
            capital = float(rng.lognormal(mean=9.0, sigma=1.0))
            biases = ["overconfidence", "loss_aversion", "herd", "contrarian", "anchoring", "recency"]
            bias = rng.choice(biases)

            horizons_by_type = {
                "hft": "scalper",
                "institutional": "swing",
            }
            horizon = horizons_by_type.get(trader_type, "intraday")

            profiles.append(
                TraderProfile(
                    agent_id=f"{trader_type}_{i:03d}",
                    trader_type=trader_type,
                    persona=persona,
                    risk_appetite=risk,
                    capital=capital,
                    information_edge=_default_edge(trader_type),
                    time_horizon=horizon,
                    behavioral_bias=bias,
                )
            )

    return profiles[:total_agents]


def _build_persona_prompt(trader_type: str, count: int) -> str:
    """Build prompt to generate diverse personas for a trader type."""
    return f"""Generate {count} unique, diverse personas for "{trader_type}" cryptocurrency traders.

Each persona should be 2-3 sentences describing their:
- Trading strategy and decision-making process
- Risk tolerance and position sizing approach
- Unique behavioral quirk or bias

Return ONLY a JSON array of strings, each being one persona description.
Example: ["Persona 1 description...", "Persona 2 description..."]

Make each persona distinctly different from others - vary their experience level,
confidence, reaction to losses, and specific strategy details."""


def _parse_persona_response(text: str, expected_count: int) -> list[str]:
    """Parse LLM response into list of persona strings."""
    import json

    text = text.strip()

    # Try direct JSON parse
    try:
        result = json.loads(text)
        if isinstance(result, list):
            return [str(p) for p in result]
    except json.JSONDecodeError:
        pass

    # Try extracting from code block
    if "```" in text:
        parts = text.split("```")
        for part in parts[1::2]:
            clean = part.strip()
            if clean.startswith("json"):
                clean = clean[4:].strip()
            try:
                result = json.loads(clean)
                if isinstance(result, list):
                    return [str(p) for p in result]
            except json.JSONDecodeError:
                continue

    # Try finding array in text
    start = text.find("[")
    end = text.rfind("]") + 1
    if start >= 0 and end > start:
        try:
            result = json.loads(text[start:end])
            if isinstance(result, list):
                return [str(p) for p in result]
        except json.JSONDecodeError:
            pass

    logger.warning(f"Failed to parse persona response, using defaults")
    return [ARCHETYPE_PERSONAS.get("noise", "You are a trader.")] * expected_count
